CREATE TABLE chat (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    title VARCHAR NOT NULL,
    description VARCHAR NOT NULL
);

-- Создание таблицы chat_user
CREATE TABLE chat_user (
    id SERIAL PRIMARY KEY,
    chat_id INTEGER NOT NULL,
    user_id UUID NOT NULL,
    FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE message(
 id SERIAL PRIMARY KEY,
 text VARCHAR NOT NULL,
 chat_id INTEGER NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP,
 FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);

