[package]
name = "logbook-app-back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono", "uuid"] }
dotenvy = "0.15.7"
tokio = { version = "1", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
axum-extra = { version = "0.9.2", features = ["cookie"] }
serde_json = "1.0"
axum = "0.7.4"
tower-http = { version = "0.5.1", features = ["trace"] }
tower = { version = "0.4", features = ["util"] }
hyper = "1.1.0"
regex = "1.5"
jsonwebtoken = "9.2.0"
bcrypt = "0.15.0"
http = "1.0.0"
utoipa = { version = "4.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = {version = "6.0.0", features = ["axum"] }
utoipa-redoc = { version = "3.0.0", features = ["axum"] }
utoipa-rapidoc = { version = "3.0.0", features = ["axum"] }
chrono = {version = "0.4.34", features = ['serde']}
cargo-watch = "8.5.2"
lettre = "0.11.4"
argon2 = "0.5.3"
rand_core = "0.6.4"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
time = "0.3.20"
redis = "0.25.2"

[[bin]]
name = "axum_api_with_auth"
path = "src/main.rs"
