version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_dump:/pg_dumb
  logbook:
    build: .
    volumes:
     - .:/logbook-app-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    image: aleksej177/logbook  
    environment:
      DATABASE_URL: postgres://postgres:postgres@db/logbook
      POSTGRES_DB: logbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      APP_PROTOCOL: http://
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      JWT_REFRESH_SECRET: my_ultra_secure_secret_refresh_secret
      JWT_ACCESS_SECRET: my_ultra_secure_access_secret
      JWT_ACCESS_EXPIRED_IN: 60
      JWT_REFRESH_EXPIRED_IN: 10080
      SMTP_USERNAME: dive-logbook@yandex.ru
      SMTP_PASSWORD: "lvknwlldeubagwbv"
      SMTP_TRANSPORT: smtp.yandex.ru
      REDIS_PORT: redis://127.0.0.1/
    restart: unless-stopped
volumes:
  pg_data: