global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'logbook'
    static_configs:
      - targets: ['logbook:9464']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']