name: test deploy

on:
  push:
    branches:
      - master

jobs:
  my_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.TIMWEB_USERNAME }}
          SSH_HOST: ${{ secrets.TIMWEB_HOST }}
          SSH_KEY: ${{ secrets.TIMWEB_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/server.key
          chmod 600 ~/.ssh/server.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/server.key
            StrictHostKeyChecking no
          END

      - name: Running deploy script
        run: ssh server '
            rm -rf -f ~/logbook-back/*
            && cd logbook-back
            && git clone -b master git@github.com:PudovAlexey/logbook-back.git docker-compose.yml
            && docker pull aleksej177/logbook:latest
            && docker-compose down
            && docker-compose up -d
          '