name: test deploy

on:
  push:
    branches:
      - master

jobs:
  my_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: echo Timeweb
        uses: appleboy/ssh-action@master
        with:
          host: 37.77.104.138
          username: root
          key: ssh root@37.77.104.138
          password: wmoXot5m6,*4G*
          script:
            ssh-keyscan -H 37.77.104.138 >> ~/.ssh/known_hosts
            echo "hello world"