name: test deploy

on:
  push:
    branches:
      - master

jobs:
  my_build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: pudo-aleksej@yandex.ru
          password: Laborador1478

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      - name: echo Timeweb
        uses: appleboy/ssh-action@master
        with:
          host: 37.77.104.138
          username: root
          key: ssh root@37.77.104.138
          password: wmoXot5m6,*4G*
          script:
            ssh-keyscan -H 37.77.104.138 >> ~/.ssh/known_hosts
            echo "hello world"
            git clone git@github.com:PudovAlexey/logbook-back.git /tmp/logbook-back
            cd /tmp/logbook-back
            docker-compose pull
            docker-compose down
            docker-compose up -d